sonar.host.url=http://localhost:9000
sonar.token=squ_b05d76e610caa9141b28019d6acdedf12363abec

sonar.projectKey=sistema-comercial-frontend
sonar.projectName=sistema-comercial-frontend
sonar.sources=src
sonar.exclusions=src/test.ts, src/**/*.spec.ts, node_modules/**
sonar.sourceEncoding=UTF-8